### ISSUE TITLE
Usage instructions missing some info

### ISSUE THREAD

**Issue by po5i** [kanekotic/oauth-electron-twitter#2]
For react newbees could be useful how to use the `window` param:

I tried: 

    const {BrowserWindow} = require('electron').remote
    var authWindow = new BrowserWindow({ 
      width: 450, 
      height: 300, 
      show: false,
      //parent: mainWindow, 
      modal: true, 
      webPreferences: {
        nodeIntegration:false
      } 
    });
    auth.login(info, authWindow);

with no success.  Any help?

**Comment by alvarolorentedev** [comment]
i will give it a go, do you have an example project? i can test this fast?.
i am using it in my plugin system 
https://github.com/Hatisoft/koteky/blob/aa889ec76de3074b87df4c04d37cb518d29b451f/lib/main/app-module.js#L32-L38
https://github.com/Hatisoft/koteky-twitter/blob/f8ce13c3d9ca24c67fc5ceaada716686461c305e/lib/provider-twitter.js#L43-L56
Let me know if its just the documentation is weak or is something diferent, i will change in any case. thanks for the feedback.

**Comment by po5i** [comment]
Neat! 

Now I got it working, I think if you add some little details to your current documentation could be more understandable for react beginners:



Declare a twitter object, and use it as parameter for the OAuth in conjunction with the electron window used to display the login

    var window = new BrowserWindow({webPreferences: {nodeIntegration: false}});
    var info = new twitter("key","secret");
    var auth = new oauth();

The login function will return a Promise with the access token and secret

    auth.login(info, window)
         .then((result) => {
               console.log(result);
               window.close();
          })

The output in the console will be:

    {
        oauth_access_token: ***,
        oauth_access_token_secret: ***
    }

**Comment by alvarolorentedev** [comment]
sure, thanks a lot for the improvement all is helpful.

Let me know if you need anything else. 

I will close this issue ok?

**Comment by designbyadrian** [comment]
A full example would be great for n00bs who don't know what BrowserWindow is.
